version: '3'
services:
  flask:
      container_name: minitter
      image: "21jun/minitter"
      ports:
       - "5000:5000"
      networks:
      - backend
  nginx:
      container_name: minitter-nginx
      image: "21jun/minitter-nginx"
      ports:
       - "80:80"
      networks:
       - backend

networks:
  backend:
    driver: bridge