version: '3'
services:
  flask:
      container_name: flask-base
      image: "21jun/flask-base"
      ports:
       - "5000:5000"
      networks:
      - backend
  nginx:
      container_name: flask-nginx
      image: "21jun/flask-base-nginx"
      ports:
       - "80:80"
      networks:
       - backend

networks:
  backend:
    driver: bridge