"""empty message

Revision ID: 635b622add8d
Revises: e33b55c60185
Create Date: 2020-08-14 17:10:33.629196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635b622add8d'
down_revision = 'e33b55c60185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('user', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('user', 'u_name')
    op.drop_column('user', 'u_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('u_id', sa.INTEGER(), nullable=False))
    op.add_column('user', sa.Column('u_name', sa.VARCHAR(), nullable=False))
    op.drop_column('user', 'name')
    op.drop_column('user', 'id')
    # ### end Alembic commands ###
